### ISSUE TITLE
debian 10/11: Certificate validation failed

### ISSUE THREAD

**Issue by FJerusalem** [nbuchwitz/check_opnsense#5]
Hi there - using debian 10 and 11:

Even though I'm using the -k -switch to turn off certificate-validation I'm getting the following error:
./check_opnsense.py -k -H myopnsensebox.local --api-key "*******" --api-secret "*******" -m updates
UNKNOWN - Could not connect to OPNsense: Certificate validation failed

Any ideas on that?

Already tried setting verify=False in the script with the same result...
Best regards and thanks in advance.

Florian

**Comment by DerRueter** [comment]
> Hi there - using debian 10 and 11:
> 
> Even though I'm using the -k -switch to turn off certificate-validation I'm getting the following error: ./check_opnsense.py -k -H myopnsensebox.local --api-key "_******" --api-secret "******_" -m updates UNKNOWN - Could not connect to OPNsense: Certificate validation failed
> 
> Any ideas on that?
> 
> Already tried setting verify=False in the script with the same result... Best regards and thanks in advance.
> 
> Florian

Hi Florian

try adding the Port parameter -p 443 after changing verify=False.

`./check_opnsense.py -k -H opnsense.local -p 443 --api-key xxx --api-secret xxx -m updates`

Best regards

Alexander

**Comment by FJerusalem** [comment]
Doh. Wayyyyy to obvious. Thanks - that fixed it of course!
